service: beanservice

provider:
  name: aws
  runtime: java8
  stage: dev
  region: eu-central-1

package:
  artifact: build/libs/hello-dev-all.jar

functions:
  onConnect:
    handler: com.camtittle.beanservice.ConnectHandler
    events:
      - websocket:
          route: $connect
          routeResponseSelectionExpression: $default

resources:
  Resources:
    beanUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: beanClients
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
            - AttributeName: connectionId
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      dbPath: "./"

plugins:
  - serverless-dynamodb-local
  - serverless-offline